- hosts: all
  roles:
    - { role: volumes, when: instance_store_enabled | default(false) | bool }
    - { role: "dev-sec.os-hardening", when: ansible_hardening | default(false) | bool }
    - { role: "dev-sec.ssh-hardening", when: ansible_hardening | default(false) | bool }
    - insight_infra.chainlink
